name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Run weekly on main branch
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
        pip install pytest pytest-benchmark locust

    - name: Install ML dependencies
      run: |
        # These are optional but needed for comprehensive testing
        pip install google-cloud-storage
        pip install pandas numpy scikit-learn statsmodels
    
    - name: Run dataset processing performance tests
      run: |
        python tests/performance/dataset_processing_test.py --output performance_report.json
    
    - name: Run API performance tests with Locust
      run: |
        # Start API server in background
        python -m src.api.server --server-type fastapi &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Run performance tests
        locust -f tests/performance/locustfile.py --headless -u 10 -r 1 --run-time 5m --host http://localhost:8080
        
        # Stop server
        kill $SERVER_PID
    
    - name: Check for performance regression
      run: |
        python tests/performance/check_regression.py --current performance_report.json --threshold 10
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: |
          performance_report.json
          locust_stats.csv